# Generated by Django 4.0 on 2022-08-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
